sudo: false
jdk: oraclejdk8
language: scala

scala:
   - 2.11.12
   - 2.12.7

matrix:
   include:
      - env: PLAY_VERSION=2.5.19
        scala: 2.11.12
      - scala: 2.12.7
        jdk: openjdk8
      - scala: 2.12.7
        jdk: openjdk11
   allow_failures:
      # Java 11 is still not fully supported. It is good that we are already
      # testing our sample applications to better discover possible problems
      # but we can allow failures here too.
      - jdk: openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
#  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
